services:
  mongo.db.product:
    restart: always  # Container her durduğunda yeniden başlat
    image: mongo:8.0-rc  # MongoDB 8.0 RC imajı
    container_name: mongo.db.product.container  
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}  
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD} 
    ports:
      - "27030:27017"  # Host:27030 → Container:27017 port yönlendirme => host makinenin 27030 portunu container'ın 27017 portuna yönlendirir
    volumes:
      - mongo.db.product.volume:/data/db  # Verileri kalıcı hale getirmek için volume

  # Mongo-Express Service (Web Arayüzü)
  mongo.db.product.ui:
    image: mongo-express:1.0.2-20-alpine3.19  # Mongo-Express imajı
    container_name: mongo.db.product.ui  
    ports:
      - "27032:8081"  # Host:27032 → Container:8081 port yönlendirme
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo.db.product:27017/"
      ME_CONFIG_BASICAUTH: "false"  # HTTP basic auth kapalı  => yani kısaca şifresiz erişime izin veriyor
    depends_on:
      - mongo.db.product  # Önce MongoDB'nin başlamasını bekle
  keycloak:
    restart: always
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0
    command: start
    environment:
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT: false 
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres.db.keycloak/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres.db.keycloak
  postgres.db.keycloak:
    restart: always
    image: postgres:16.2
    container_name: postgres.db.keycloak.container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - posrgres.db.keycloak.volume:/var/lib/postgresql/data
  postgres.db.keycloak.ui:
    restart: always
    image: dpage/pgadmin4
    container_name: postgres.db.keycloak.container.ui
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - posrgres.db.keycloak.ui.volume:/var/lib/pgadmin

volumes:
  mongo.db.product.volume:  # MongoDB verileri için named volume
  posrgres.db.keycloak.volume:
  posrgres.db.keycloak.ui.volume: